---
name: "\U0001F41B How to do ...?"
description: How do I do X or Y with the Devilbox?
title: "[Howto]: "
labels: ["question"]
assignees:
  - cytopia

body:

  - type: checkboxes
    attributes:
      label: Have you already checked elsewhere?
      description: You may select more than one.
      options:
        - label: I have checked the [Devilbox forum](https://devilbox.discourse.group/)
        - label: I have checked the [Devilbox documentation](https://devilbox.readthedocs.io/en/latest/)
        - label: I have googled already with no luck

  - type: textarea
    attributes:
      label: What do you want to do?
      description: Tell us, what you want to do that you are struggling with
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is the goal?
      description: Tell us, what is the goal that you want to accomplish?
    validations:
      required: true
