# vim: set ft=yaml:
---
version: '2.3'

# ------------------------------------------------------------
# Yaml Default
# ------------------------------------------------------------

x-app: &default-php
  env_file:
    - ./.env

  environment:
    ##
    ## Debug/Logging
    ##
    - DEBUG_ENTRYPOINT=${DEBUG_ENTRYPOINT:-2}
    - DOCKER_LOGS=1

    ##
    ## Enable/Disable PHP Modules
    ##
    - ENABLE_MODULES=${PHP_MODULES_ENABLE}
    - DISABLE_MODULES=${PHP_MODULES_DISABLE}

    ##
    ## Mail-catching
    ##
    - ENABLE_MAIL=${PHP_MAIL_CATCH_ALL:-2}
  dns:
    - 172.16.238.100

  volumes:
    # ---- Format: ----
    # HOST-DIRECTORY : DOCKER-DIRECTORY

    # Mount custom mass virtual hosting
    - ${HOST_PATH_HTTPD_DATADIR}:/shared/httpd:rw${MOUNT_OPTIONS}

    # Mount Mail directory
    - devilbox-mail:/var/mail:rw${MOUNT_OPTIONS}

    # Mount devilbox user-defined *.ini files in order
    # to overwrite the default PHP.ini configuration
    - ${DEVILBOX_PATH}/cfg/php-ini-${PHP_SERVER}:/etc/php-custom.d:ro${MOUNT_OPTIONS}

    # Mount devilbox user-defined PHP-FPM *.conf files in order
    # to overwrite the default PHP-FPM configuration
    - ${DEVILBOX_PATH}/cfg/php-fpm-${PHP_SERVER}:/etc/php-fpm-custom.d:ro${MOUNT_OPTIONS}

    # Mount devilbox user-defined PHP-FPM startup *.sh scripts
    - ${DEVILBOX_PATH}/cfg/php-startup-${PHP_SERVER}:/startup.1.d:rw${MOUNT_OPTIONS}
    - ${DEVILBOX_PATH}/autostart:/startup.2.d:rw${MOUNT_OPTIONS}

    # Mount devilbox user-defined supervisord config
    - ${DEVILBOX_PATH}/supervisor:/etc/supervisor/custom.d:rw${MOUNT_OPTIONS}

    # Certificate Authority public key
    - ${DEVILBOX_PATH}/ca:/ca:rw${MOUNT_OPTIONS}

  depends_on:
    - bind


# ------------------------------------------------------------
# PHP Services
# ------------------------------------------------------------
services:
  php54:
    <<: *default-php
    image: devilbox/php-fpm:5.4-prod-0.147
    hostname: php54
    networks:
      app_net:
        ipv4_address: 172.16.238.201

  php55:
    <<: *default-php
    image: devilbox/php-fpm:5.5-prod-0.147
    hostname: php55
    networks:
      app_net:
        ipv4_address: 172.16.238.202

  php56:
    <<: *default-php
    image: devilbox/php-fpm:5.6-prod-0.147
    hostname: php56
    networks:
      app_net:
        ipv4_address: 172.16.238.203

  php70:
    <<: *default-php
    image: devilbox/php-fpm:7.0-prod-0.147
    hostname: php70
    networks:
      app_net:
        ipv4_address: 172.16.238.204

  php71:
    <<: *default-php
    image: devilbox/php-fpm:7.1-prod-0.147
    hostname: php71
    networks:
      app_net:
        ipv4_address: 172.16.238.205

  php72:
    <<: *default-php
    image: devilbox/php-fpm:7.2-prod-0.147
    hostname: php72
    networks:
      app_net:
        ipv4_address: 172.16.238.206

  php73:
    <<: *default-php
    image: devilbox/php-fpm:7.3-prod-0.147
    hostname: php73
    networks:
      app_net:
        ipv4_address: 172.16.238.207

  php74:
    <<: *default-php
    image: devilbox/php-fpm:7.4-prod-0.147
    hostname: php74
    networks:
      app_net:
        ipv4_address: 172.16.238.208

  php80:
    <<: *default-php
    image: devilbox/php-fpm:8.0-prod-0.147
    hostname: php80
    networks:
      app_net:
        ipv4_address: 172.16.238.209

  php81:
    <<: *default-php
    image: devilbox/php-fpm:8.1-prod-0.147
    hostname: php81
    networks:
      app_net:
        ipv4_address: 172.16.238.210

  php82:
    <<: *default-php
    image: devilbox/php-fpm:8.2-prod-0.147
    hostname: php82
    networks:
      app_net:
        ipv4_address: 172.16.238.211
